import { checkOrganization } from './check-organization-flows.mjs'
import assert from 'node:assert/strict'
import { spawn } from 'node:child_process'
import { mkdir, readFile } from 'node:fs/promises'
import { existsSync } from 'node:fs'
import path from 'node:path'
import { fileURLToPath } from 'node:url'
import { scryptSync } from 'node:crypto'
import { chromium, request } from 'playwright'

const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..')
const backendPort = Number(process.env.MEMBERS_TEST_API_PORT || 3107)
const frontendPort = Number(process.env.MEMBERS_TEST_PORT || 5177)
const apiURL = `http://127.0.0.1:${backendPort}`
const baseURL = `http://127.0.0.1:${frontendPort}`
const artifacts = path.join(root, 'artifacts', 'members')
const dataFile = path.join(artifacts, `workspace-${Date.now()}.json`)
const children = new Set()
await mkdir(artifacts, { recursive: true })
function start(script, args, env) {
  const child = spawn(process.execPath, [script, ...args], { cwd: root, env: { ...process.env, MEMBERS_PROVIDER: 'local', MEMBER_USERNAME: 'admin', MEMBER_PASSWORD_HASH: `test-salt:${scryptSync('123', 'test-salt', 64).toString('hex')}`, ...env }, windowsHide: true, stdio: ['ignore', 'pipe', 'pipe'] })
  children.add(child)
  child.on('exit', () => children.delete(child))
  let output = ''
  child.stdout.on('data', data => { output += data })
  child.stderr.on('data', data => { output += data })
  child.on('error', error => { output += error.message })
  return { child, output: () => output }
}
async function ready(url, server) {
  for (let attempt = 0; attempt < 100; attempt++) {
    if (server.child.exitCode !== null) throw new Error(server.output())
    try { if ((await fetch(url)).ok) return } catch {}
    await new Promise(resolve => setTimeout(resolve, 200))
  }
  throw new Error(`Server unavailable: ${url}\n${server.output()}`)
}
function backend() { return start('backend/dist/index.js', [], { PORT: String(backendPort), NODE_ENV: 'test', MEMBER_DATA_FILE: dataFile }) }
let apiServer = backend()
const vite = start('node_modules/vite/bin/vite.js', ['frontend', '--host', '127.0.0.1', '--port', String(frontendPort), '--strictPort'], { API_PROXY_TARGET: apiURL })
let browser
let api
try {
  await Promise.all([ready(`${apiURL}/api/members/auth/session`, apiServer), ready(`${baseURL}/login`, vite)])
  api = await request.newContext({ baseURL: apiURL })
  assert.equal((await api.get('/api/members/workspace')).status(), 401)
  assert.equal((await api.post('/api/members/goals', { headers: { 'X-Caesar-Client': 'members' }, data: {} })).status(), 401)
  assert.equal((await api.post('/api/members/auth/login', { data: { username: 'admin', password: '123' } })).status(), 403)
  assert.equal((await api.post('/api/members/auth/login', { headers: { 'X-Caesar-Client': 'members' }, data: { username: 'admin', password: 'incorrect' } })).status(), 401)
  const headers = { 'X-Caesar-Client': 'members' }
  const login = await api.post('/api/members/auth/login', { headers, data: { username: 'admin', password: '123' } })
  assert.equal(login.status(), 200)
  assert.match(login.headers()['set-cookie'], /HttpOnly/)
  assert.match(login.headers()['set-cookie'], /SameSite=Strict/)
  assert.equal((await api.get('/api/members/workspace')).status(), 200)
  const seed = await (await api.get('/api/members/workspace')).json()
  assert.equal((await api.post('/api/members/goals', { headers, data: { ...seed.goals[0], progress: 101 } })).status(), 400)
  assert.equal((await api.post('/api/members/entries', { headers, data: { ...seed.entries[0], teamId: '', projectId: '' } })).status(), 400)
  assert.equal((await api.post('/api/members/entries', { headers, data: { ...seed.entries[0], date: '2026-02-30' } })).status(), 400)
  assert.equal((await api.post('/api/members/projects', { headers, data: { ...seed.projects[0], targetDate: '2025-01-01' } })).status(), 400)
  assert.equal((await api.post('/api/members/updates', { headers, data: { ...seed.updates[0], teamId: 'missing' } })).status(), 400)
  const preflight = await api.fetch('/api/members/goals', { method: 'OPTIONS', headers: { Origin: 'https://example.com', 'Access-Control-Request-Method': 'POST', 'Access-Control-Request-Headers': 'x-caesar-client' } })
  assert.equal(preflight.headers()['access-control-allow-origin'], undefined)
  console.log('PASS API authorization, cookie flags, cross-origin write protection and input validation')

  const installedBrowser = ['C:/Program Files/Google/Chrome/Application/chrome.exe', 'C:/Program Files (x86)/Microsoft/Edge/Application/msedge.exe'].find(file => existsSync(file))
  browser = await chromium.launch({ executablePath: process.env.BROWSER_PATH || installedBrowser, headless: true })
  const context = await browser.newContext({ viewport: { width: 1440, height: 1000 }, reducedMotion: 'reduce' })
  const page = await context.newPage()
  page.setDefaultTimeout(12000)
  const errors = []
  page.on('pageerror', error => errors.push(error.message))
  for (const route of ['dashboard', 'dashboard/teams/avionics', 'dashboard/goals', 'dashboard/data', 'dashboard/projects/phobos', 'dashboard/activity', 'dashboard/unknown']) {
    await page.goto(`${baseURL}/${route}`)
    await page.waitForURL(`${baseURL}/login`)
    await page.getByRole('button', { name: 'Sign in', exact: true }).waitFor()
    assert.equal(await page.locator('.m-sidebar').count(), 0)
  }
  assert.doesNotMatch(await page.locator('body').innerText(), /\badmin\b|\b123\b/i)
  await page.screenshot({ path: path.join(artifacts, 'login-desktop.png'), fullPage: true })
  await page.getByLabel('Username', { exact: true }).fill('admin')
  await page.getByLabel('Password', { exact: true }).fill('wrong')
  await page.getByRole('button', { name: 'Sign in', exact: true }).click()
  await page.getByRole('alert').filter({ hasText: 'Incorrect username or password' }).waitFor()
  await page.getByLabel('Password', { exact: true }).fill('123')
  await page.getByRole('button', { name: 'Sign in', exact: true }).click()
  await page.waitForURL(`${baseURL}/dashboard`)
  await page.getByRole('heading', { name: 'Welcome back, Admin.' }).waitFor()
  assert.equal(await page.evaluate(() => document.cookie.includes('caesar_member')), false)
  await page.screenshot({ path: path.join(artifacts, 'overview-desktop.png'), fullPage: true })
  console.log('PASS protected deep links, invalid login, hidden credentials and successful sign in')

  const nav = page.getByRole('navigation', { name: 'Members navigation' })
  const dialog = page.getByRole('dialog')
  async function saved(button) {
    await dialog.getByRole('button', { name: button, exact: true }).click()
    await dialog.waitFor({ state: 'hidden' })
    await page.getByRole('status').filter({ hasText: 'Changes saved' }).waitFor()
  }
  await nav.getByRole('link', { name: 'Teams', exact: true }).click()
  await page.getByRole('button', { name: 'Create team' }).click()
  await dialog.getByLabel('Team name').fill('Systems test team')
  await dialog.getByLabel('Description').fill('Integration and verification team for the portal check.')
  await dialog.getByLabel('Members').fill('Test lead, Test engineer')
  await dialog.getByLabel('Current project').selectOption('phobos')
  await dialog.getByLabel('Status').selectOption('In Progress')
  await saved('Create team')
  await page.getByRole('link', { name: 'Systems test team', exact: true }).click()
  await page.getByRole('heading', { name: 'Systems test team', exact: true }).waitFor()
  const teamId = new URL(page.url()).pathname.split('/').pop()
  await page.getByRole('button', { name: 'Edit team' }).click()
  await dialog.getByLabel('Members').fill('Test lead, Test engineer, Reviewer')
  await saved('Save changes')
  await page.locator('.m-member-chips').getByText('Reviewer', { exact: false }).waitFor()

  await nav.getByRole('link', { name: 'Projects', exact: true }).click()
  await page.getByRole('button', { name: 'Create project' }).click()
  await dialog.getByLabel('Project name').fill('Integration verification')
  await dialog.getByLabel('Team', { exact: true }).selectOption(teamId)
  await dialog.getByLabel('Description').fill('A test project for complete documentation flows.')
  await dialog.getByLabel('Target date').fill('2027-12-01')
  await saved('Create project')
  await page.getByRole('link', { name: 'Integration verification', exact: true }).click()
  const projectId = new URL(page.url()).pathname.split('/').pop()
  await page.getByRole('button', { name: 'Edit project' }).click()
  await dialog.getByLabel('Status').selectOption('In Progress')
  await saved('Save changes')

  await page.getByRole('button', { name: 'Create goal' }).click()
  await dialog.getByLabel('Title', { exact: true }).fill('Validate telemetry logging')
  await dialog.getByLabel('Description').fill('Check the end-to-end documentation workflow.')
  await dialog.getByLabel('Deadline').fill('2027-10-20')
  await dialog.getByLabel('Status').selectOption('In Progress')
  await dialog.getByRole('slider').fill('60')
  await saved('Create goal')
  await page.getByRole('button', { name: 'Edit goal' }).click()
  await dialog.getByLabel('Status').selectOption('Completed')
  await saved('Save changes')
  assert.equal(await page.getByRole('progressbar', { name: 'Validate telemetry logging' }).getAttribute('aria-valuenow'), '100')

  await page.getByRole('button', { name: 'Post update' }).click()
  await dialog.getByLabel('Title', { exact: true }).fill('Telemetry workflow checked')
  await dialog.getByLabel('Description').fill('The integration result is ready to review.')
  await dialog.getByLabel('Tags (optional)').fill('integration, testing')
  await saved('Create update')
  await page.getByRole('heading', { name: 'Telemetry workflow checked' }).waitFor()
  await page.getByRole('button', { name: 'Edit update' }).click()
  await dialog.getByLabel('Description').fill('The integration result is ready to review. Notes verified.')
  await saved('Save changes')

  await page.getByRole('button', { name: 'Add data entry' }).click()
  await dialog.getByLabel('Title', { exact: true }).fill('Telemetry sample rate')
  await dialog.getByLabel('Description').fill('A sample sensor measurement for the automated check.')
  await dialog.getByLabel('Category', { exact: true }).fill('Electronics testing')
  await dialog.getByLabel('Value', { exact: true }).fill('125.5')
  await dialog.getByLabel('Unit (optional)').fill('Hz')
  await dialog.getByLabel('Notes (optional)').fill('Illustrative test entry, not a real rocket measurement.')
  await dialog.getByLabel('Date', { exact: true }).fill('2026-09-26')
  await saved('Create data entry')
  await page.getByRole('button', { name: 'Telemetry sample rate', exact: true }).click()
  await page.getByText('Illustrative test entry, not a real rocket measurement.', { exact: true }).waitFor()
  await page.getByRole('button', { name: 'Edit Telemetry sample rate', exact: true }).click()
  await dialog.getByLabel('Value', { exact: true }).fill('126.25')
  await saved('Save changes')
  await page.reload()
  await page.getByRole('button', { name: 'Telemetry sample rate', exact: true }).waitFor()
  assert.match(await page.locator('.m-data-table').innerText(), /126\.25/)
  console.log('PASS creation, editing, project relationships, goal completion and persistence after reload')

  await nav.getByRole('link', { name: 'Data', exact: true }).click()
  await page.getByLabel('Search records').fill('Telemetry sample')
  await page.getByLabel('Team', { exact: true }).selectOption(teamId)
  await page.getByLabel('Project', { exact: true }).selectOption(projectId)
  await page.getByLabel('Category', { exact: true }).selectOption('Electronics testing')
  await page.getByLabel('From date').fill('2026-09-26')
  await page.getByLabel('To date').fill('2026-09-26')
  assert.equal(await page.locator('.m-record-title').count(), 1)
  await page.getByLabel('From date').fill('2026-09-27')
  await page.getByRole('alert').waitFor()
  assert.equal(await page.locator('.m-record-title').count(), 0)
  await page.getByRole('button', { name: 'Clear filters' }).click()
  assert.equal(await page.locator('.m-record-title').count(), seed.entries.length + 1)
  await nav.getByRole('link', { name: 'Activity', exact: true }).click()
  assert.match(await page.locator('.m-activity-list').innerText(), /Systems test team completed a goal: Validate telemetry logging/)
  assert.match(await page.locator('.m-activity-list').innerText(), /posted an update: Telemetry workflow checked/)
  await nav.getByRole('link', { name: 'Goals', exact: true }).click()
  await page.getByLabel('Team', { exact: true }).selectOption(teamId)
  await page.getByLabel('Status', { exact: true }).selectOption('Completed')
  assert.equal(await page.locator('.m-goal-card').count(), 1)
  console.log('PASS combined filters, inclusive dates, invalid date range, goal filters and activity logging')

  for (const width of [1440, 768, 390, 320]) {
    await page.setViewportSize({ width, height: 900 })
    for (const route of ['dashboard', 'dashboard/teams', 'dashboard/goals', 'dashboard/data', `dashboard/projects/${projectId}`, 'dashboard/activity']) {
      await page.goto(`${baseURL}/${route}`)
      await page.locator('#members-main').waitFor()
      assert.equal(await page.evaluate(() => document.documentElement.scrollWidth > window.innerWidth), false, `Overflow on ${route} at ${width}px`)
    }
    if (width <= 700) {
      await page.getByRole('button', { name: 'Open navigation' }).click()
      await nav.getByRole('link', { name: 'Overview', exact: false }).click()
      await page.getByRole('heading', { name: 'Welcome back, Admin.' }).waitFor()
      assert.equal(await page.locator('#members-menu').getAttribute('aria-expanded'), 'false')
      await page.getByRole('button', { name: 'Post update' }).click()
      assert.equal(await dialog.evaluate(el => el.scrollWidth <= el.clientWidth), true)
      await page.keyboard.press('Escape')
      await dialog.waitFor({ state: 'hidden' })
      assert.equal(await page.getByRole('button', { name: 'Post update' }).evaluate(el => document.activeElement === el), true)
      await page.screenshot({ path: path.join(artifacts, `overview-${width}.png`), fullPage: true })
    }
    console.log(`PASS ${width}px: all sections, layout and mobile navigation`)
  }
  await page.setViewportSize({ width: 1440, height: 1000 })
  await page.goto(`${baseURL}/dashboard/data`)
  await page.getByRole('heading', { name: 'Collected data', exact: true }).waitFor()
  await page.screenshot({ path: path.join(artifacts, 'data-desktop.png'), fullPage: true })
  await page.getByRole('button', { name: 'Add data entry' }).click()
  await dialog.getByLabel('Title', { exact: true }).fill('Unsent measurement')
  await dialog.getByLabel('Team', { exact: true }).selectOption(teamId)
  await dialog.getByLabel('Description').fill('Preserve these notes when saving fails.')
  await dialog.getByLabel('Value', { exact: true }).fill('42')
  await page.route('**/api/members/entries', route => route.fulfill({ status: 503, contentType: 'application/json', body: JSON.stringify({ error: 'Test service unavailable.' }) }))
  await dialog.getByRole('button', { name: 'Create data entry', exact: true }).click()
  await dialog.getByRole('alert').filter({ hasText: 'Test service unavailable.' }).waitFor()
  assert.equal(await dialog.getByLabel('Title', { exact: true }).inputValue(), 'Unsent measurement')
  await dialog.getByRole('button', { name: 'Cancel', exact: true }).click()
  await page.unroute('**/api/members/entries')
  await checkOrganization(page, baseURL, 'local-organization', artifacts)
  // Simulate a session revoked elsewhere, then navigate with stale client state.
  await context.request.post(`${baseURL}/api/members/auth/logout`, { headers })
  await nav.getByRole('link', { name: 'Teams', exact: true }).click()
  await page.waitForURL(`${baseURL}/login`)
  await page.getByLabel('Username', { exact: true }).fill('admin')
  await page.getByLabel('Password', { exact: true }).fill('123')
  await page.getByRole('button', { name: 'Sign in', exact: true }).click()
  await page.getByRole('heading', { name: 'Welcome back, Admin.' }).waitFor()
  await page.getByRole('button', { name: 'Sign out', exact: true }).click()
  await page.waitForURL(`${baseURL}/login`)
  assert.equal((await context.request.get(`${baseURL}/api/members/workspace`)).status(), 401)
  await page.goBack()
  await page.waitForURL(`${baseURL}/login`)
  await page.setViewportSize({ width: 390, height: 844 })
  await page.getByRole('button', { name: 'Sign in', exact: true }).waitFor()
  assert.equal(await page.evaluate(() => document.documentElement.scrollWidth > innerWidth), false)
  await page.screenshot({ path: path.join(artifacts, 'login-mobile.png'), fullPage: true })
  const stored = JSON.parse(await readFile(dataFile, 'utf8'))
  assert.equal(stored.entries.find(entry => entry.title === 'Telemetry sample rate').value, 126.25)
  await new Promise(resolve => { apiServer.child.once('exit', resolve); apiServer.child.kill() })
  apiServer = backend()
  await ready(`${apiURL}/api/members/auth/session`, apiServer)
  assert.equal((await api.get('/api/members/workspace')).status(), 401, 'Restart must invalidate memory sessions')
  await api.post('/api/members/auth/login', { headers, data: { username: 'admin', password: '123' } })
  const restored = await (await api.get('/api/members/workspace')).json()
  assert.equal(restored.entries.find(entry => entry.title === 'Telemetry sample rate').value, 126.25)
  const productionPort = backendPort + 1
  const production = start('backend/dist/index.js', [], { PORT: String(productionPort), NODE_ENV: 'production', MEMBER_DATA_FILE: dataFile })
  const productionURL = `http://127.0.0.1:${productionPort}`
  await ready(`${productionURL}/api/members/auth/session`, production)
  const productionPage = await context.newPage()
  await productionPage.goto(`${productionURL}/new/dashboard/projects/phobos`)
  await productionPage.waitForURL(`${productionURL}/new/login`)
  await productionPage.getByRole('button', { name: 'Sign in', exact: true }).waitFor()
  const productionLogin = await api.post(`${productionURL}/api/members/auth/login`, { headers, data: { username: 'admin', password: '123' } })
  assert.equal(productionLogin.status(), 200)
  assert.match(productionLogin.headers()['set-cookie'], /Secure/)
  await productionPage.close()
  assert.deepEqual(errors, [], 'Browser runtime errors')
  console.log('PASS failed-save recovery, revoked sessions, sign-out, browser back protection and restart persistence')
  console.log('PASS production /new/ routing, Secure cookies and no browser errors')
} finally {
  await browser?.close()
  await api?.dispose()
  for (const child of children) child.kill()
}
