import { Fragment, useState } from 'react'
import type { DataEntry } from './api'
import { useWorkspace } from './context'
import { AddButton, dateLabel, Empty, PageHeading } from './components'

export function DataTable({ entries, compact = false }: { entries: DataEntry[]; compact?: boolean }) {
  const { data, edit } = useWorkspace()
  const [expanded, setExpanded] = useState<string | null>(null)
  if (!entries.length) return <Empty title="No data entries found">Add a measurement or adjust the filters to see results.</Empty>
  return <div className="m-table-scroll" role="region" aria-label="Collected data" tabIndex={0}><table className="m-data-table"><thead><tr><th scope="col">Record / team</th><th scope="col">Category</th>{!compact && <th scope="col">Project</th>}<th scope="col">Value</th><th scope="col">Date</th><th scope="col"><span className="m-sr-only">Actions</span></th></tr></thead><tbody>{[...entries].sort((a, b) => b.date.localeCompare(a.date)).map(entry => <Fragment key={entry.id}><tr><th scope="row"><button className="m-record-title" aria-expanded={expanded === entry.id} aria-controls={`entry-${entry.id}`} onClick={() => setExpanded(expanded === entry.id ? null : entry.id)}>{entry.title}</button><span>{data.teams.find(team => team.id === entry.teamId)?.name || 'Project record'}</span></th><td><span className="m-category">{entry.category}</span></td>{!compact && <td>{data.projects.find(project => project.id === entry.projectId)?.name || '—'}</td>}<td className="m-data-value">{entry.value.toLocaleString('en-GB', { maximumFractionDigits: 12 })} <span>{entry.unit}</span></td><td className="m-nowrap">{dateLabel(entry.date)}</td><td><button className="m-text-link" aria-label={`Edit ${entry.title}`} onClick={() => edit({ entity: 'entries', id: entry.id })}>Edit</button></td></tr><tr id={`entry-${entry.id}`} hidden={expanded !== entry.id} className="m-data-detail"><td colSpan={compact ? 5 : 6}><strong>Description</strong><p>{entry.description}</p><strong>Notes</strong><p>{entry.notes || 'No notes added.'}</p></td></tr></Fragment>)}</tbody></table></div>
}
export default function DataPage() {
  const { data, edit } = useWorkspace()
  const [search, setSearch] = useState('')
  const [team, setTeam] = useState('')
  const [project, setProject] = useState('')
  const [category, setCategory] = useState('')
  const [from, setFrom] = useState('')
  const [to, setTo] = useState('')
  const invalidRange = Boolean(from && to && from > to)
  const entries = data.entries.filter(entry => !invalidRange && (!team || entry.teamId === team) && (!project || entry.projectId === project) && (!category || entry.category === category) && (!from || entry.date >= from) && (!to || entry.date <= to) && `${entry.title} ${entry.description} ${entry.notes} ${entry.value} ${entry.unit}`.toLowerCase().includes(search.toLowerCase()))
  return <><PageHeading eyebrow="04 / Engineering records" title="Collected data" description="Every observation adds to the mission. Keep your results in one place." action={<AddButton onClick={() => edit({ entity: 'entries' })}>Add data entry</AddButton>} /><div className="m-data-summary"><IconLabel value={data.entries.length} label="DOCUMENTED ENTRIES" /><IconLabel value={new Set(data.entries.map(entry => entry.category)).size} label="DATA CATEGORIES" /><IconLabel value={new Set(data.entries.map(entry => entry.teamId).filter(Boolean)).size} label="CONTRIBUTING TEAMS" /></div><section className="m-panel m-data-panel"><div className="m-filters m-data-filters"><label className="m-search">Search records<input type="search" value={search} onChange={event => setSearch(event.target.value)} placeholder="Search title, notes or value…" /></label><label>Team<select aria-label="Team" value={team} onChange={event => setTeam(event.target.value)}><option value="">All teams</option>{data.teams.map(team => <option key={team.id} value={team.id}>{team.name}</option>)}</select></label><label>Project<select aria-label="Project" value={project} onChange={event => setProject(event.target.value)}><option value="">All projects</option>{data.projects.map(project => <option key={project.id} value={project.id}>{project.name}</option>)}</select></label><label>Category<select aria-label="Category" value={category} onChange={event => setCategory(event.target.value)}><option value="">All categories</option>{[...new Set(data.entries.map(entry => entry.category))].sort().map(category => <option key={category}>{category}</option>)}</select></label><label>From<input aria-label="From date" type="date" value={from} onChange={event => setFrom(event.target.value)} /></label><label>To<input aria-label="To date" type="date" value={to} onChange={event => setTo(event.target.value)} /></label><button className="m-button" onClick={() => { setSearch(''); setTeam(''); setProject(''); setCategory(''); setFrom(''); setTo('') }}>Clear filters</button></div>{invalidRange && <p className="m-error" role="alert">The end date must be on or after the start date.</p>}<div className="m-table-caption" role="status">{entries.length} of {data.entries.length} entries · Select a record to read its description and notes.</div><DataTable entries={entries} /></section></>
}
function IconLabel({ value, label }: { value: number; label: string }) { return <div><strong>{value.toString().padStart(2, '0')}</strong><span>{label}</span></div> }
